### ISSUE TITLE
The King can capture a piece that would put him into check

### ISSUE THREAD

**Issue by JonathanYiv** [lujanfernaud/ruby-chess#1]
![example](https://user-images.githubusercontent.com/29989755/30006486-99de9a92-90c7-11e7-965b-147b7c9149d7.png)

Player 2 moved a pawn to check the King, and this pawn was defended by another pawn
The king was allowed to capture the pawn checking the king
when I tried to have player 2 capture the king, an error arose

**Comment by lujanfernaud** [comment]
@JonathanYiv Hey! Thanks for reporting this issue and for the details.

This case should have already been covered. I'll check it.
